version: '3.7'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: springbootdb
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    volumes:
      - ./start.sql:/docker-entrypoint-initdb.d/start.sql
    ports:
      - "3306:3306"
    networks:
      - app-network

  backend:
    build:
      context: ./server
    container_name: backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springbootdb?useSSL=false&serverTimezone=UTC&characterEncoding=UTF-8
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network

  frontend:
    build:
      context: ./front
    container_name: frontend
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "4200:4200"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
